### ISSUE TITLE
BUG: KQX SE_Kernel unreachable code

### ISSUE THREAD

**Issue by HaoZeke** [avishart/CatLearn#1]
https://github.com/avishart/CatLearn/blob/08ec12b978abc0a8b6ecb1aaa321b3c07d082be2/catlearn/regression/gaussianprocess/kernel/se.py#L42-L56

The last line is never reached (in practice the derivatives are always used for prediction) and also it should possibly be K in any case?

**Comment by avishart** [comment]
Hi @HaoZeke,
You are right that the last line should just be K. 
However, it should be possible to just predict and train on function values (or energies).
